baseURL = 'https://rye.moe/'
languageCode = 'en-us'
title = 'RyeBread'
theme="lynx"

[author]
  name = "RyeBread"
  headline = "A Delightful Crumb Trail to My Creative Endeavors"
  image = "rye-bread.png"
  links = [
    { github = "https://github.com/ryebreadgit" },
    { email = "mailto:info@rye.moe" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
